name: "lein test: all"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test docker opts work in GHA env before gvisor
        run: |
          docker --version
          docker run \
              -i \
              --rm ubuntu:18.04 true
          docker run \
              --network=none \
              -i \
              --rm ubuntu:18.04 true
          docker run \
              --network=none \
              --ipc=private \
              -i \
              --rm ubuntu:18.04 true
          docker run \
              --network=none \
              --ipc=private \
              --memory 1g \
              --cap-drop=ALL \
              -i \
              --rm ubuntu:18.04 true
      - name: install runsc
        run: |
          sudo curl --fail -o /usr/local/bin/runsc https://storage.googleapis.com/gvisor/releases/nightly/2019-11-11/runsc
          echo "3a3ea9ef6d6f8f23e4748af925e23811946d719d5542e09e5afbadc086543cef2a69d78843683f2ec683d93395eb59c8738d791ca037d86832ded307465e9db3  /usr/local/bin/runsc" | sha512sum -c -
          sudo chmod a+x /usr/local/bin/runsc
          sudo /usr/local/bin/runsc install -- --platform=ptrace
          sudo systemctl restart docker
      - name: test docker opts work in GHA env with gvisor
        run: |
          docker run \
              -i \
              --rm ubuntu:18.04 true || exit 1
          docker run --runtime=runsc \
              -i \
              --rm ubuntu:18.04 true || exit 2
          docker run --runtime=runsc \
              --network=none \
              -i \
              --rm ubuntu:18.04 true
          docker run --runtime=runsc \
              --network=none \
              --ipc=private \
              -i \
              --rm ubuntu:18.04 true || exit 3
          docker run --runtime=runsc \
              --network=none \
              --ipc=private \
              --memory 1g \
              --cap-drop=ALL \
              -i \
              --rm ubuntu:18.04 true || exit 4

      - name: build docker images
        run: |
          cd docker-build
          ./build-all.sh
      - name: leiningen tests
        run: |
          export LEIN_HOME="/home/runner/work"
          curl --fail -o /home/runner/work/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod a+x /home/runner/work/lein
          /home/runner/work/lein test :all
